replicaCount: 2

image:
  repository: 533267450054.dkr.ecr.us-east-1.amazonaws.com/mcp-registry
  # tag is set by Makefile via --set image.tag=

containerPort: 8080

service:
  port: 8080

ingress:
  host: registry.nimblebrain.ai
  certificateArn: arn:aws:acm:us-east-1:533267450054:certificate/825ee262-8e93-4ba6-97be-fdc33084cad3

healthCheck:
  path: /v0.1/health

env:
  NODE_ENV: "production"
  LOG_LEVEL: "info"

externalSecret:
  enabled: false

serviceMonitor:
  enabled: true

grafanaDashboard:
  enabled: true
